package sc.fawanews.app.data

import kotlinx.serialization.json.Json
import org.mozilla.javascript.Context
import org.mozilla.javascript.ContextFactory
import org.mozilla.javascript.RhinoException
import java.net.URI

/**
 * Runs a game page's own inline scripts against stand-in video players and records the
 * links the page hands them. The site keeps reshaping how it hides links (renamed lists,
 * split strings, loops); a browser simply runs the code, and so does this.
 */
object PageScriptRunner {
    private const val MAX_INSTRUCTIONS = 5_000_000
    private const val INSTRUCTIONS_KEY = "fawa.instructions"

    private val scriptBlockRegex = Regex(
        """<script\b([^>]*)>(.*?)</script>""",
        setOf(RegexOption.IGNORE_CASE, RegexOption.DOT_MATCHES_ALL),
    )
    private val externalSrcRegex = Regex("""\bsrc\s*=""", RegexOption.IGNORE_CASE)
    private val assetRegex = Regex("""\.(js|css|png|jpe?g|gif|svg|webp|ico|html?)(\?|$)""", RegexOption.IGNORE_CASE)

    private class TooMuchWork : Error()

    private val factory = object : ContextFactory() {
        override fun makeContext(): Context = super.makeContext().apply {
            // Android cannot load generated bytecode, and only the interpreter counts instructions.
            @Suppress("DEPRECATION")
            optimizationLevel = -1
            languageVersion = Context.VERSION_ES6
            instructionObserverThreshold = 10_000
        }

        override fun observeInstructionCount(cx: Context, instructionCount: Int) {
            val used = (cx.getThreadLocal(INSTRUCTIONS_KEY) as? Int ?: 0) + instructionCount
            cx.putThreadLocal(INSTRUCTIONS_KEY, used)
            if (used > MAX_INSTRUCTIONS) throw TooMuchWork()
        }
    }

    fun findStreamUrls(html: String, pageUrl: String = FawaRepository.BASE_URL): List<String> {
        val blocks = scriptBlockRegex.findAll(html)
            .filterNot { externalSrcRegex.containsMatchIn(it.groupValues[1]) }
            .map { it.groupValues[2] }
            .filter { it.isNotBlank() }
            .toList()
        if (blocks.isEmpty()) return emptyList()

        val cx = factory.enterContext()
        return try {
            cx.putThreadLocal(INSTRUCTIONS_KEY, 0)
            // Safe objects only: page code gets no access to Java classes.
            val scope = cx.initSafeStandardObjects()
            cx.evaluateString(scope, PRELUDE, "prelude", 1, null)
            for (block in blocks) {
                try {
                    cx.evaluateString(scope, block, "page", 1, null)
                } catch (_: RhinoException) {
                    // A broken ad script must not stop the rest, same as in a browser.
                } catch (_: TooMuchWork) {
                    break
                }
            }
            cx.putThreadLocal(INSTRUCTIONS_KEY, 0)
            try {
                cx.evaluateString(scope, "__runTimers()", "timers", 1, null)
            } catch (_: RhinoException) {
            } catch (_: TooMuchWork) {
            }
            cx.putThreadLocal(INSTRUCTIONS_KEY, 0)
            val found = cx.evaluateString(scope, "JSON.stringify(__collect())", "collect", 1, null)
            Json.decodeFromString<List<String>>(Context.toString(found))
                .mapNotNull { absolute(pageUrl, it.trim()) }
                .filterNot { assetRegex.containsMatchIn(it) }
                .distinct()
        } catch (_: RhinoException) {
            emptyList()
        } catch (_: TooMuchWork) {
            emptyList()
        } finally {
            Context.exit()
        }
    }

    private fun absolute(pageUrl: String, link: String): String? {
        if (link.isEmpty() || link.contains(' ')) return null
        val resolved = runCatching { URI(pageUrl).resolve(link).toString() }.getOrNull() ?: return null
        return resolved.takeIf { it.startsWith("http://") || it.startsWith("https://") }
    }

    private val PRELUDE = """
        var window = this, self = this, top = this, parent = this, globalThis = this;
        var __found = [];
        Math.random = function() { return 0; };
        function __add(v) {
          if (v == null) return;
          if (typeof v === 'string') { __found.push(v); return; }
          if (typeof v !== 'object') return;
          if (typeof v.length === 'number') { for (var i = 0; i < v.length; i++) __add(v[i]); return; }
          __add(v.source); __add(v.sources); __add(v.src); __add(v.file); __add(v.url); __add(v.playlist);
        }
        var __timers = [];
        function setTimeout(f) { if (typeof f === 'function') __timers.push(f); return __timers.length; }
        var setInterval = setTimeout;
        function clearTimeout() {}
        var clearInterval = clearTimeout;
        function requestAnimationFrame(f) { return setTimeout(f); }
        function __runTimers() {
          for (var i = 0; i < __timers.length && i < 50; i++) { try { __timers[i](); } catch (e) {} }
        }
        function __element(tag) {
          var el = {
            tagName: String(tag || 'div').toUpperCase(), style: {}, dataset: {}, children: [], innerHTML: '',
            classList: { add: function() {}, remove: function() {}, toggle: function() {}, contains: function() { return false; } },
            appendChild: function(c) { this.children.push(c); return c; },
            removeChild: function(c) { return c; }, insertBefore: function(c) { return c; },
            setAttribute: function(k, v) { if (k === 'src' || k === 'data-src') __add(String(v)); this[k] = v; },
            getAttribute: function(k) { return this[k] || null; },
            addEventListener: function() {}, removeEventListener: function() {},
            querySelector: function() { return __element(); }, querySelectorAll: function() { return []; },
            play: function() {}, pause: function() {}, load: function() {}, canPlayType: function() { return 'maybe'; }
          };
          var src = '';
          Object.defineProperty(el, 'src', { get: function() { return src; }, set: function(v) { src = String(v); __add(src); } });
          return el;
        }
        var document = {
          body: __element('body'), head: __element('head'), documentElement: __element('html'),
          cookie: '', referrer: '', readyState: 'complete', title: '',
          location: { href: 'http://www.fawanews.sc/', host: 'www.fawanews.sc', hostname: 'www.fawanews.sc',
                      protocol: 'http:', pathname: '/', search: '', hash: '', reload: function() {} },
          getElementById: function() { return __element(); },
          getElementsByTagName: function() { return [__element()]; },
          getElementsByClassName: function() { return []; },
          querySelector: function() { return __element(); }, querySelectorAll: function() { return []; },
          createElement: function(t) { return __element(t); }, createTextNode: function() { return __element(); },
          write: function() {}, writeln: function() {},
          addEventListener: function(n, f) { if (typeof f === 'function') __timers.push(f); },
          removeEventListener: function() {}
        };
        var location = document.location;
        var history = { go: function() {}, back: function() {} };
        var navigator = { userAgent: 'Mozilla/5.0 (Linux; Android 13) AppleWebKit/537.36 Chrome/120.0.0.0 Mobile Safari/537.36',
                          language: 'en-US', languages: ['en-US'], platform: 'Linux armv8l', cookieEnabled: true };
        var screen = { width: 1920, height: 1080 };
        var localStorage = { getItem: function() { return null; }, setItem: function() {}, removeItem: function() {} };
        var sessionStorage = localStorage;
        var console = { log: function() {}, warn: function() {}, error: function() {}, info: function() {}, debug: function() {} };
        function addEventListener(n, f) { if (typeof f === 'function') __timers.push(f); }
        function removeEventListener() {}
        function alert() {}
        function confirm() { return false; }
        function open() { return null; }
        function atob(s) {
          var k = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
          s = String(s).replace(/[^A-Za-z0-9+\/]/g, '');
          var out = '', bits = 0, n = 0;
          for (var i = 0; i < s.length; i++) {
            bits = (bits << 6) | k.indexOf(s.charAt(i)); n += 6;
            if (n >= 8) { n -= 8; out += String.fromCharCode((bits >> n) & 255); }
          }
          return out;
        }
        function ${'$'}(x) {
          if (typeof x === 'function') __timers.push(x);
          var q = {};
          var chain = function() { return q; };
          ['on', 'click', 'html', 'text', 'attr', 'css', 'append', 'find', 'each', 'hide', 'show', 'addClass', 'removeClass'].forEach(function(m) { q[m] = chain; });
          q.ready = function(f) { if (typeof f === 'function') __timers.push(f); return q; };
          return q;
        }
        var jQuery = ${'$'};
        var Clappr = {
          Player: function(o) {
            __add(o);
            this.attachTo = function() {}; this.play = function() {}; this.on = function() {};
            this.load = function(s) { __add(s); }; this.configure = function(c) { __add(c); };
          },
          Events: {}
        };
        function jwplayer() {
          var p = {};
          p.setup = function(o) { __add(o); return p; }; p.load = function(o) { __add(o); return p; };
          p.on = function() { return p; }; p.play = function() { return p; };
          return p;
        }
        function Hls() {
          this.loadSource = function(u) { __add(u); }; this.attachMedia = function() {};
          this.on = function() {}; this.destroy = function() {};
        }
        Hls.isSupported = function() { return true; };
        Hls.Events = {};
        function videojs() {
          var p = {};
          p.src = function(s) { __add(s); return p; }; p.ready = function() { return p; };
          p.play = function() { return p; }; p.on = function() { return p; };
          return p;
        }
        function Playerjs(o) { __add(o); }
        var dashjs = { MediaPlayer: function() { return { create: function() { return {
          initialize: function(e, u) { __add(u); }, attachSource: function(u) { __add(u); }
        }; } }; } };
        var aclib = { runPop: function() {}, runAutoTag: function() {} };
        function __collect() {
          var out = [];
          for (var i = 0; i < __found.length; i++) out.push(String(__found[i]));
          // Media links left in page variables, for players this file does not stand in for.
          var media = /^(https?:)?\/\/\S+\.(m3u8|mpd)(\?|$)/i;
          var names = Object.keys(window);
          for (var j = 0; j < names.length; j++) {
            if (names[j].indexOf('__') === 0) continue;
            var v = window[names[j]];
            if (typeof v === 'string' && media.test(v)) out.push(v);
            else if (v && typeof v === 'object' && typeof v.length === 'number') {
              for (var k = 0; k < v.length; k++) if (typeof v[k] === 'string' && media.test(v[k])) out.push(v[k]);
            }
          }
          return out;
        }
    """.trimIndent()
}
